# Generated by Django 5.2.5 on 2025-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
